#https://python-catalin.blogspot.no/2017/03/take-weather-data-with-pyowm-from.html
#https://github.com/csparpa/pyowm/blob/master/pyowm/docs/usage-examples.md

import pyowm

print("Have a account to openweathermap.org and use with api key free or pro")
print("owm = pyowm.OWM(API_key='your-API-key', subscription_type='pro'")

owm = pyowm.OWM("327407589df060c7f825b63ec1d9a096")
location = "Bergen, Norway"
forecast = owm.daily_forecast(location)
tomorrow = pyowm.timeutils.tomorrow()
forecast.will_be_sunny_at(tomorrow)

observation = owm.weather_at_place(location)
w = observation.get_weather()
print(w)
print("Weather details")
print("=============== ")

print("Get cloud coverage")
print(w.get_clouds())
print("---------------")
print("Get rain volume")
print(w.get_rain())
print("---------------")
print("Get snow volume")
print(w.get_snow())

print("Get wind degree and speed")
print(w.get_wind())
print("---------------")
print("Get humidity percentage")
print(w.get_humidity())
print("---------------")
print("Get atmospheric pressure")
print(w.get_pressure())
print("---------------")
print("Get temperature in Kelvin degs")
print(w.get_temperature())
print("---------------")
print("Get temperature in Celsius degs")
print(w.get_temperature(unit='celsius'))
print("---------------")
print("Get temperature in Fahrenheit degs")
print(w.get_temperature('fahrenheit'))
print("---------------")
print("Get weather short status")
print(w.get_status())
print("---------------")
print("Get detailed weather status")
print(w.get_detailed_status())
print("---------------")
print("Get OWM weather condition code")
print(w.get_weather_code())
print("---------------")
print("Get weather-related icon name")
print(w.get_weather_icon_name())
print("---------------")
print("Sunrise time (ISO 8601)")
print(w.get_sunrise_time('iso'))
print("Sunrise time (GMT UNIXtime)")
print(w.get_sunrise_time())
print("---------------")
print("Sunset time (ISO 8601)")
print(w.get_sunset_time('iso'))
print("Sunset time (GMT UNIXtime)")
print(w.get_sunset_time())
print("---------------")
print("Search current weather observations in the surroundings of")
print("Latitude and longitude coordinates for: ", location)
observation_list = owm.weather_around_coords(47.46, 26.30)

print("---------------")
reg = owm.city_id_registry()
print(reg.ids_for('Bergen', 'NO'))       # [ (123, 'London', 'GB'), (456, 'London', 'MA'), (789, 'London', 'WY')])
print(reg.locations_for('Bergen', 'NO'))  # gives a list of Location instances
print("---------------")